### ISSUE TITLE
Broken mount scripts

### ISSUE THREAD

**Issue by oSumAtrIX** [ReVanced/revanced-library#29]
Currently, mount scripts are being created for patched applications when they are deployed to a device. Rebooting the device shows, that the mount scripts do not work properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-library/commit/10f8cd1470fd29cfefe53bf00a4a014f71a3f706

**Comment by severtheskyline** [comment]
It seems that Magisk v28 broke the current method of root mounting, at least with the CLI, the apps simply don't mount after rebooting.

**Comment by oSumAtrIX** [comment]
Open a new issus
